### ISSUE TITLE
Error found!

### ISSUE THREAD

**Issue by sam619** [alekseynemiro/nemiro.oauth.dll#10]
These errors found when i building the app...

I have installed **nemiro.OAuth.LoginForms** package... but for the first time if i am going to building the app these bugs raised!

1	The type or namespace name **'DropboxLogin**' could not be found (are you missing a using directive or an assembly reference?)	C:\Users\Sony\Documents\Visual Studio 2010\Projects\Dropbox\Dropbox\Form1.cs	

2	The type or namespace name '**Nemiro**' could not be found (are you missing a using directive or an assembly reference?)	C:\Users\Sony\Documents\Visual Studio 2010\Projects\Dropbox\Dropbox\Form1.cs	

3	The type or namespace name '**Nemiro**' could not be found (are you missing a using directive or an assembly reference?)	C:\Users\Sony\Documents\Visual Studio 2010\Projects\Dropbox\Dropbox\Form1.cs

**Comment by alekseynemiro** [comment]
Please see: [The type or namespace name 'Nemiro' could not be found](http://oauth.nemiro.net/?topic=error.html).

If the problem persists:

1\. Make sure that the assembly **Nemiro.OAuth** and **Nemiro.OAuth.LoginForms** is referenced into your project.

2\. Make sure that the namespaces **Nemiro.OAuth** and **Nemiro.OAuth.LoginForms** is imported into your class (**Form1.cs** and other):

```C#
using Nemiro.OAuth;
using Nemiro.OAuth.LoginForms;
```

3\. Make sure that you use the latest versions of packages.
Run the following command in the **Package Manager Console**:
```
PM> Update-Package Nemiro.OAuth.LoginForms -Version 1.4
```

**NOTE:** Make sure you have the latest version of **Nuget**. 
Menu **Tools** -> **Extension Manager** select **NuGet Package Manager** and you can see version number. Latest: **v2.8**.

**Comment by sam619** [comment]
Thank you sir, It works... Actually, I was using .NET Framework 4 client profile. Now i have selected correct .NET Freamwork 4. Thank you! It works... :) :+1: :8ball:

**Comment by sam619** [comment]
Thank you sir, It works... Actually, I was using **.NET Framework 4 client profile**. Now i have selected correct **.NET Freamwork 4**. Thank you! It works... :) :+1:
