### ISSUE TITLE
Error found! 

### ISSUE THREAD

**Issue by sam619** [alekseynemiro/nemiro.oauth.dll#11]
![abc](https://cloud.githubusercontent.com/assets/14121545/15629862/e1a498d2-2542-11e6-86c0-b47320bccbb5.jpg)

File uploading issue!!!

**Comment by alekseynemiro** [comment]
Perhaps the problem with Internet access.

Check the firewall settings.

Try to open https://api-content.dropbox.com in your browser.

If the problem persists, please show your code.

**Comment by sam619** [comment]
Ok sir... Thank you!

**Comment by sam619** [comment]
Sir, I am uploading file from winform app, upto 1 gb file. it didn't uploaing, Its showing this error
![sa](https://cloud.githubusercontent.com/assets/14121545/15648159/5562a4dc-2686-11e6-8bf8-870ba8d5d156.png)

**Comment by alekseynemiro** [comment]
https://github.com/alekseynemiro/nemiro.oauth.dll/issues/12

**Comment by smile36** [comment]
hi,

![ekran alintisi](https://cloud.githubusercontent.com/assets/19752192/15801582/282d32aa-2aa2-11e6-929a-822db137b7ec.PNG)

**Comment by smile36** [comment]
when I test instagram I got this error {"code": 403, "error_type": "OAuthForbiddenException", "error_message": "You are not a sandbox user of this client"}

**Comment by alekseynemiro** [comment]
* http://stackoverflow.com/questions/34765854/how-to-be-an-instagram-sandbox-user-for-any-client-in-instagram
* https://www.instagram.com/developer/sandbox/
