### ISSUE TITLE
Custom OAuth2 server

### ISSUE THREAD

**Issue by alzritm** [alekseynemiro/nemiro.oauth.dll#14]
Я хочу реализовать свой сервер авторизации (http://tools.ietf.org/html/rfc6749#section-4.3.2), а в качестве клиента использовать вашу библиотеку.

Вы не могли бы вкратце описать обмен между сервером и клиентом ?

PS Код сервера (рабочий) с меня :-)

**Comment by alekseynemiro** [comment]
Я уже год не занимался этим проектом, так что не помню всех нюансов. Лучше делать в соответствии со спецификацией.

На вскидку, у других это реализовано примерно так:

В базе поставщика **OAuth** создается приложение. Как минимум, необходим уникальный идентификатор приложения (как правило обычный числовой счетчик), секретный ключ (произвольная строка небольшого размера, что-нибудь типа **guid**) и список разрешенных адресов возврата. Последнее можно не делать, но в целях безопасности лучше сделать. 

Человеческое название приложения тоже понадобится, чтобы пользователю было понятно, какому приложению он дает разрешения. Иконки, описание, ссылки на сайт, лицензия и т.п. по вкусу. Чем все будет проще, тем лучше.

Клиент **OAuth** генерирует для пользователя ссылку, по которой пользователь может пройти процедуру аутентификации на сервере поставщика **OAuth**.

В ссылке обязательно указывается идентификатор приложения - **client_id**. Желаемый тип ответа сервера - **response_type**. Адрес возврата - **redirect_uri**. Дополнительно можно указать список необходимых разрешений - **scope** (обычно список разрешений через запятую, типа: email, friends, photos).  И любую другую информацию в параметре **state**.

**response_type** может иметь значение:
* **code** - сервер возвращает код авторизации, который клиент должен конвертировать в маркер доступа (**access token**);
* **token** - сервер возвращает маркер доступа.

Сервер разбирает полученные параметры. Смотрит, известен ему пользователь или нет (в **cookies**). Если пользователь не известен, то выдает форму аутентификации (ввода логина и пароля). Если пользователь известен, переводит к странице запроса разрешений, которые требует приложение. Пользователь либо соглашается, либо отказывается. 

Если пользователь дал разрешения, то сервер создает код авторизации или сразу маркер доступа, в зависимости от **response_type** и собственных возможностей.

Если пользователь отказался давать разрешения или сервер не смог обработать правильно полученные в ссылке параметры, или еще что-то пошло не так, то на страницу обратного вызова должен быть передан параметр **error**, содержащий [код причины отказа](https://tools.ietf.org/html/rfc6749#section-4.1.2.1), а также может быть передан параметр **error_description** с подробным описанием проблемы.

Если все нормально и **response_type** имеет значение **code**, то сервер создает временный код авторизации (в базе данных, помимо самого кода, следует записать как минимум **client_id**, **redirect_uri** и **state**). Срок жизни кода авторизации должен быть ограничен (минут 5-10 вполне хватит). Клиент (клинское приложение) получает этот код в параметрах **redirect_uri**, конкретно в параметре **code** и на его основе формирует запрос на получение маркера доступа.
В запросе передает полученный код авторизации (**code**), идентификатор приложения (**client_id**), секретный ключ (**client_secret**), адрес возврата (**redirect_uri**, который был изначально) и **grant_type**. В данном примере **grant_type** всегда будет иметь значение **authorization_code**.

По **redirect_uri** сервер может проверить, что запрос не был подделан. По **client_id** сервер может найти приложение в базе и проверить **client_secret**.

Если все нормально, то сервер создает и возвращает маркер доступа (**access token**):
```JSON
{ 
  "access_token": "маркер доступа - это может быть строка, типа guid",
  "expires_in": "срок действия - количество секунд (опционально)",
  "token_type": "типа маркера: обычно bearer - указывает клиенту, как использовать маркер",
  "scope": "область действия (опционально)",
  "state": "если был указан в ссылке авторизации"
}
```
Маркер хранится в базе. При последующих запросах, сервер проверяет либо наличие в запросе параметра **access_token** (потенциально небезопасно), либо **HTTP** заголовок **Authorization** (наиболее надежный вариант). Как именно проверять **Authorization**, зависит от **token_type**. Если `token_type=bearer`, то в заголовке ожидается строка вида: `Bearer маркерДоступаКакЕсть` (это один из самых простых вариантов).

Примерно так :-) Но вообще, все сложнее.

**Comment by alzritm** [comment]
Спасибо
