### ISSUE TITLE
Facebook Client on windows forms

### ISSUE THREAD

**Issue by alexanderbahmatov** [alekseynemiro/nemiro.oauth.dll#15]
Hello. Im using ur library for auth  on facebook by windows forms. Using example from http://www.codeproject.com/Articles/875991/Users-Authorization-through-OAuth-in-NET-Framework#WindowsForms
but I have the next issue: after trying clicking on button and opening child window - element webbrowser  throw exception, that 
Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.
What need to do to fix this problem?

**Comment by alekseynemiro** [comment]
1. Create your application on **Facebook**.
2. Get the **application ID** and **application key**. Use the application ID and application key.
3. Add addresses that you need in your application settings.

![default](https://cloud.githubusercontent.com/assets/6204692/17882773/4293beb2-6917-11e6-80e3-99e144761aba.png)
