### ISSUE TITLE
Facebook Client - No Email returned

### ISSUE THREAD

**Issue by filmico** [alekseynemiro/nemiro.oauth.dll#16]
Hi Aleksey!

First of alll, thanks a lot for the library as it is awsome all the work you´ve done on it!
Sorry to bother you but, the facebook Client is not returning me the email.

I´ve followed the documentation of the library, and all the samples provided on the following pages but can not get back the user email for the Facebook provider.

http://www.codeproject.com/Articles/875991/Users-Authorization-through-OAuth-in-NET-Framework#NETVersionRemark
https://oauth4net.codeplex.com/

The samples provided are not returning the email either.

**All works fine in you demo site http://demo-oauth.nemiro.net/   but I cannot get same behaviour.**  

A side note:

I´m using VB.NET and the framework 3.5 and I´ve also tested this in the global.asax

OAuthManager.RegisterClient _
(
  "facebook", 
  "1435890xxxxxx808", 
  "c6057dfae3xxxxxxxxxa4182e8fd"
)

and 

        OAuthManager.RegisterClient _
        (
          New FacebookClient _
          (
            "1056832xxxxxxx7",
            "b724e6822aeb4faxxxxxxxxxxx4fb"
          ) With
          {
            .Scope = "public_profile,email,user_friends"
          }
        )

Do I need to publish the site or all should works on the local host? (Of course I´ve added the local host url and all that stuffs to the facebook developers section)

I´ve uploaded the small test here: https://www.dropbox.com/s/iut9zh8hlg08hun/Ejemplo_05.zip?dl=0

cheers,

**Comment by alekseynemiro** [comment]
Perhaps the problem is in the [application settings](https://developers.facebook.com/apps/). 

Or in the security settings of a particular user.

https://developers.facebook.com/docs/facebook-login/permissions/#reference-email:

> Note, even if you request the email permission it is not guaranteed you will get an email address. For example, if someone signed up for Facebook with a phone number instead of an email address, the email field may be empty.

--

In the localhost should work as well as on the public server.

I set its own application ID and secret key in your code. Facebook returned my email address.

**Comment by filmico** [comment]
Thanks a lot for your reply!!

I´ve reviewed the app settings and also created another one for testing purpose and all looks ok at the Facebook Developers site. A friend of mine has replicated the test by creating a new app on his developer network account and tested with the same project and his email does not return too.

I know not all the accounts will return an email but the fact that works on your demo site and the test you´ve performed is driving me nuts to discover where is the problem!

Here you can see my app settings.

![facebook_app_setting](https://cloud.githubusercontent.com/assets/16740569/17902133/72b2b8ee-693c-11e6-9f86-783c31dd50ef.jpg)
![facebook_app_setting2](https://cloud.githubusercontent.com/assets/16740569/17902132/72ac42ac-693c-11e6-8227-c997dccc8189.jpg)
![facebook_app_setting3](https://cloud.githubusercontent.com/assets/16740569/17902134/72b4de1c-693c-11e6-81f6-af57b263fc7e.jpg)

Any idea that might help us to fix the issue we are experiencing?

P.S. Searching on the web I found other users with this same problem against facebook.
There´s one comment at the bottom of this page. 
http://www.codeproject.com/Articles/875991/Users-Authorization-through-OAuth-in-NET-Framework#NETVersionRemark

Thanks in advance!

**Comment by alekseynemiro** [comment]
I have same settings.

I have created a new application and I see the same problem :-)

I found the cause of the problem - **Graph API** version.

**Comment by alekseynemiro** [comment]
I made beta version:
https://www.nuget.org/packages/Nemiro.OAuth/1.12.0-beta2567

```
PM> Install-Package Nemiro.OAuth -Pre
```

Thank you for reporting an issue!

**Comment by filmico** [comment]
Wooowww......Aleksey
I´m jumping from the chair with a big smile :+1: 
I did not figure the issue was related to the FB Api version.
It´s working great now!!!
Thanks a lot for the fix! :100:
