### ISSUE TITLE
How to pass parameters from initial page after the login and the redirect?

### ISSUE THREAD

**Issue by rrivani** [alekseynemiro/nemiro.oauth.dll#18]
In the sample,
How to pass parameter from default.aspx to redirecttoauth.aspx, then back to externalloginresult.aspx?

Thanks

**Comment by alekseynemiro** [comment]
Just add a parameters into the return address.

```C#
OAuthWeb.RedirectToAuthorization
(
  "facebook", 
  "http://example.org/externalloginresult.aspx?param1=123&param2=test&param3=abc"
);
```

**Comment by rrivani** [comment]
The param id=xxx is dynamic.
Google gives me the "redirect_uri_mismatch" error.
The redirect URI in the request, http://mysite.com/ExternalLoginResult.aspx?id=1, does not match the ones authorized for the OAuth client.

**Comment by alekseynemiro** [comment]
Sorry, at the moment I am unable to view the code. Probably tomorrow.

As an alternative, you can use the **Session**: `Session["id"] = 123;`

**Comment by alekseynemiro** [comment]
I released the second beta version of the library - **v1.12.0-beta2603**.

```
PM> Install-Package Nemiro.OAuth -Pre
```

If **Session** for your needs is not enough, the additional query parameters can be stored in an instance of a request for authorization.

```C#
// custom parameters in a dynamic type
OAuthWeb.RedirectToAuthorization
(
  "google", 
  "http://example.org/externalloginresult.aspx",
  new
  {
    text = "custom state",
    text2 = "you can use any type with any data",
    aaa = 123,
    bbb = "abc"
  }
);

// custom parameters as a string
OAuthWeb.RedirectToAuthorization
(
  "google", 
  "http://example.org/externalloginresult.aspx",
  "custom state"
);
```

**Comment by rrivani** [comment]
Awesome. Thanks alekseynemiro!
