### ISSUE TITLE
Assembly version numbers cause assembly loading failures at runtime

### ISSUE THREAD

**Issue by mfcollins3** [alekseynemiro/nemiro.oauth.dll#19]
I integrated your framework into an application that I built a few months ago. I had forked earlier because I needed to strong name your assemblies, and I noticed that you are now string naming. I just started upgrading today and ran into an interesting issue. It appears that you put the .NET framework version in the patch version field of the version number. For example, I am seeing 1.2.45.xxx for the .NET 4.5 version of the assembly and 1.2.451 for the .NET 4.5.1 version of the assembly. This is kind of screwy and causes issues.

I have a redistributable SDK assembly that end users can use to create extensions for my app that is compiled against .NET 4.5. However, the main desktop GUI (WinForms/WPF) is built against .NET 4.5.1. If I reference the SDK assembly in my GUI, I'm hitting assembly resolution issues at runtime because the SDK assembly is trying to load the 1.2.45.xxx version of the assembly and it is finding 1.2.451.xxx instead, and this fails with an assembly load error.

If there's no fundamental API differences between the assemblies other than they are compiled for different target versions of the .NET Framework, then the assemblies should have the exact same version number. This will allow for and support in-place upgrades with the CLR. For example, an application compiled against .NET 4.0 will upgrade and run when .NET 4.5 is installed. Likewise, an application or assembly compiled against .NET 4.5 should work when running in a .NET 4.5.1 environment. But because of the version numbering scheme that you are using, this isn't the case.

**Comment by alekseynemiro** [comment]
> I noticed that you are now string naming

Yes, I've seen your changes.
Thank you for pointing out the problem.

>  It appears that you put the .NET framework version in the patch version..

Yes that's right.

It's an old model. I do not like this.

I think it should be changed. And in the future releases most likely I'll change it.

Thank you for your message!
