### ISSUE TITLE
Problem with HttpParameterCollection

### ISSUE THREAD

**Issue by CarlJohnsonCJ** [alekseynemiro/nemiro.oauth.dll#20]
Hello! I installed your framework and tried to make first application with it. But when I try to use HttpParameterCollection I got this error: http://imgur.com/a/R1b1m. Any idead how to solve it? I use Visual studio 2015 and make windows form application with Net framework 4.0

**Comment by alekseynemiro** [comment]
Hi,

You need to add a reference to assembly **System.Web**:
Menu **Project** => **Add Reference...** 
Open **Assemblies** => **Framework** and select **System.Web**.

**Comment by CarlJohnsonCJ** [comment]
It works! Thank you very much!
