### ISSUE TITLE
Обновление маркера доступа

### ISSUE THREAD

**Issue by rutony** [alekseynemiro/nemiro.oauth.dll#21]
Доброе время суток. 
Подскажите как при использовании готового модуля сделать обновление маркера?
Я взял готовый модуль OdnoklassnikiClient или VKontakteClient, они оба поддерживают обновление маркера.
Делаю авторизацию через браузер, получаю все маркеры, в том числе маркер для обновления. Все хорошо.
Но не понятно как сделать обновление маркера без повторного подключения через браузер. Получается, что после каждого пере открытия программы нужно заново производить авторизацию через браузер, либо писать свой метод получения обновления маркера, хотя в классах определен метод RefreshToken().

**Comment by alekseynemiro** [comment]
При получении маркера доступа, в исходных данных также может содержатся `refresh_token`, который используется для получения нового маркера доступа. 

Если необходима реализация обновления маркера доступа, то после авторизации нужно извлечь и записать `refresh_token`:

```C#
string refreshToken = ((OAuth2AccessToken)result.AccessToken).RefreshToken;
// string refreshToken = ((OAuth2AccessToken)form.AccessToken).RefreshToken;
// записать в любое удобное место: в файл, в настройки приложения или базу данных
```

Для обновления маркера доступа необходимо вызвать метод **RefreshToken**, в который нужно передать **AccessToken**, содержащий `refresh_token`.

```C#
// для Windows Forms
// создаем форму
var form = new OdnoklassnikiLogin(
  "1094959360", 
  "E45991423E8C5AE249B44E84", 
  "CBACMEECEBABABABA", 
  "http://oauthproxy.nemiro.net/", 
  false, 
  false
);

// показываем форму
form.ShowDialog();

if (form.IsSuccessfully)
{
  // запоминаем RefreshToken
  string refreshToken = ((OAuth2AccessToken)form.AccessToken).RefreshToken;
  // можно в настройки сохранить

  // используем refreshToken для получения нового маркера доступа
  // для этого нужно создать новый экземпляр клиента
  var client = new OdnoklassnikiClient(
    "1094959360", 
    "E45991423E8C5AE249B44E84", 
    "CBACMEECEBABABABA"
  );
  var newAccessToken = client.RefreshToken(
    new OAuth2AccessToken("access token или empty", refreshToken)
  );
}
```

Если все пройдет успешно, то сервер вернет новый маркер доступа. Также он может вернуть новый `refresh_token`, но это не всегда так. В случае с **Одноклассники**, новый `refresh_token` при запросе на обновление не возвращается и нужно использовать первый полученный `refresh_token`.

Обновление маркера доступа поддерживается не всеми поставщиками (проверить можно по значению свойства `SupportRefreshToken`). 

**Одноклассники** позволяют обновлять маркер доступа. У **ВКонтакте** такой возможности нет.
