### ISSUE TITLE
Problems with Google authorization

### ISSUE THREAD

**Issue by AlexSandor9** [alekseynemiro/nemiro.oauth.dll#22]
Can not get back the display name.

**Comment by alekseynemiro** [comment]
I do not see any problems:
http://demo-oauth.nemiro.net

![default](https://cloud.githubusercontent.com/assets/6204692/21072068/5e5434a0-bec7-11e6-8519-8ed91c2d604f.png)

Which version are you using?
And show your code.

**Comment by AlexSandor9** [comment]
Sorry, it's my mistake, I create new account and didn't join Google+. Now it works. Can I get information about user(I need only a name) if he didn't join Google+?

**Comment by alekseynemiro** [comment]
I dont know. Try to obtain data from other **Google** services. For example: **[gmail](https://developers.google.com/gmail/api/v1/reference/users/getProfile)**.
