### ISSUE TITLE
Problems with Instagram 

### ISSUE THREAD

**Issue by Visio70** [alekseynemiro/nemiro.oauth.dll#23]
Hi. maybe only a parametrization issue but Istagram login gives an error

**Comment by alekseynemiro** [comment]
[My example](https://github.com/alekseynemiro/nemiro.oauth.dll/tree/master/examples/InstagramWinForms) is works for me. And also [demo](http://demo-oauth.nemiro.net/) is works.

Please, show your code.

If you use my example, you should specify your own application ID and secret key.

**Comment by Visio70** [comment]
Ok. I checked only the demo. I'll work on the example next week. It says "{"code": 403, "error_message": "You are not a sandbox user of this client", "error_type": "OAuthForbiddenException"}". Anyhow great job! Thanks

**Comment by alekseynemiro** [comment]
Yes, in my examples application keys for test. These keys have limited access. **Instagram** does not allow full access for the application of this type (demo, test).

You must register your own application in **Instagram** and use own **Client ID** and **Client Secret**. 

https://instagram.com/developer/clients/manage/

You are welcome!
