### ISSUE TITLE
Загрузка и выгрузка папок (Dropbox).

### ISSUE THREAD

**Issue by HappyRanger** [alekseynemiro/nemiro.oauth.dll#27]
Добрый вечер.
Подскажите,пожалуйста,как можно изменить код в DropboxExample,чтобы стало возможным загружать и выгружать не файлы,а папки? И реально ли вообще это сделать, просто даже в оригинальном Dropbox нет возможности выгрузить целую папку с компьютера, а при загрузке папок они загружаются в виде архивов.
Заранее спасибо.

**Comment by alekseynemiro** [comment]
Рекурсивно пройтись по всем подпапкам и файлам и скачать/закачать их.

В [примере загрузки](https://github.com/alekseynemiro/nemiro.oauth.dll/blob/master/examples/DropboxExample/Upload.cs) как раз используется рекурсивная загрузка файлов на сервер **Dropbox**. Если указанный путь является путем к каталогу, то вызывается метод `GetAllFiles(...)`, который получает список всех файлов в этом каталоге, и отдельно вызывается `GetAllFiles(...)` для каждой вложенной папки и так до тех пор, пока директории не закончатся.

Аналогичным образом можно сделать и скачивание. Составить список объектов и затем просто скачивать или создавать каталоги на основе этого списка.
