### ISSUE TITLE
IdentityServer 4  Integration

### ISSUE THREAD

**Issue by eflorespalma** [alekseynemiro/nemiro.oauth.dll#28]
I know you support many public clients.... But I have a STS Server Based on Asp.net Core MVC Application using IdentityServer 4...... we just implement the login page for single sign on.... but now we want all our applications use just that unique Login Page. So the problem is with Asp.net Web Forms and Asp.net MVC targeted in net framework 3.5. Is there way to do this with your library. Is There Any Example of how to implement it?. We want just erase the login page of other applications and just use the login page of the STS Server and then redirect to the Clients requested.  Thank You So Much. I hopen you can help me.

**Comment by alekseynemiro** [comment]
If **IdentityServer4** supports **OAuth**, you can make a client for **IdentityServer4**.

Example:
```C#
using System;
using Nemiro.OAuth;

public class MyClient : OAuth2Client
{

  /// <summary>
  /// Unique provider name: <b>MyClient</b>.
  /// </summary>
  public override string ProviderName
  {
    get
    {
      return "MyClient";
    }
  }

  /// <summary>
  /// Initializes a new instance of the class.
  /// </summary>
  /// <param name="clientId">The Client ID obtained from the provider website.</param>
  /// <param name="clientSecret">The Client Secret obtained from the provider website.</param>
  public MyClient(string clientId, string clientSecret) : base
  (
    "https://example.org/oauth",
    "https://example.org/oauth/access_token",
    clientId,
    clientSecret
  ) { }

  /// <summary>
  /// Gets the user details.
  /// </summary>
  /// <param name="accessToken">May contain an access token, which will have to be used in obtaining information about the user.</param>
  public override UserInfo GetUserInfo(AccessToken accessToken = null)
  {
    return new UserInfo(UniValue.Empty, null);
  }

}
```
