### ISSUE TITLE
ASP.NET Core issuse

### ISSUE THREAD

**Issue by bogdanudovichenko** [alekseynemiro/nemiro.oauth.dll#35]
NullReferenceException at Nemiro.OAuth.AuthorizationResult.get_AccessTokenValue().

When try to get access token.
OAuthWeb.VerifyAuthorization(returnedFromSocialUrl);
or
OAuthWeb.VerifyAuthorization(requestId, code);

In Full .Net framework working correct.

**Comment by alekseynemiro** [comment]
Unfortunately, the library does not support **.NET Core** and it is not planned in the current version.

**Comment by MattFromGer** [comment]
Do you plan on adding .NET Core support in the near future?
