### ISSUE TITLE
authentication via popup 

### ISSUE THREAD

**Issue by Nacer-** [alekseynemiro/nemiro.oauth.dll#4]
Hi Aleksey,
how I should do to perform the authentication operation via a popup. For example, "facebook connect" via foursquare.com.
Thank you.
Nacer.

**Comment by alekseynemiro** [comment]
Hi Nacer!

You can use parameter [display](https://developer.foursquare.com/overview/auth#display).
For pop-up you need **webpopup** value.
```C#
var client = new FoursquareClient(clientId, clientSecret);
client.Parameters = { {"display", "webpopup" } };
client.ReturnUrl = "";
client.Scope = scope;
```

Thank You! I fixed it in the [FoursquareLogin form](https://github.com/alekseynemiro/Nemiro.OAuth.LoginForms/commit/b77e8edb3efbc2b0ad441cd3d13ed8611ad5e3cf). (without creating a binary assemblies)

**Comment by alekseynemiro** [comment]
Hmm... **webpopup** does not always work correctly. Tests have shown that it is better to use the **touch** value.

[FoursquareLogin updated](https://github.com/alekseynemiro/Nemiro.OAuth.LoginForms/blob/master/src/Nemiro.OAuth.LoginForms/FoursquareLogin.cs)

**Comment by alekseynemiro** [comment]
For **web**:
```C#
OAuthManager.RegisterClient
(
  "foursquare", 
  "LHYZN1KUXN50L141QCQFNNVOYBGUE3G3FCWFZ3EEZTOZHY5Q", 
  "HWXYFLLSS2IUQ0H4XNCDAZEFZKIU3MZRP5G55TNBDHRPNOQT",
  parameters: new NameValueCollection { {"display", "touch" } }
);
```

**Comment by alekseynemiro** [comment]
It seems that **webpopup** does not work due to the fact that **Foursquare** encodes the return url.

Mode **touch** and **wap** looks like as **webpopup**. You can use it.

If you need **webpopup** mode, it is possible to perform decoding html:
```C#
OAuthWeb.VerifyAuthorization(HttpUtility.HtmlDecode(Request.Url.ToString()));
```

I need more time to understand the causes of this problem and find a solution.

**Comment by Nacer-** [comment]
Many thank's Aleksey you for your answers,

I indicated  "foursquare.com" as an example of authentication with facebook, (No relation with Nemiro.OAuth).
On foursquare.com when the visitor clicks on the link "facebook connect" (copy1), a popup opens for authentication (copy2).
With Nemiro.OAuth, if I put a link on page for authentication with Facebook, and the visitor clicks on the link "FaceBook Connect" we can not have a popup for Facebook authentication, there is a redirect to the site facebook and we remain necessarily on the same page.

I think the visitor will better apreciate the first scenario. Do you have an idea to allow this.

I have to manage multiple templates for social authentication and your dll is timely and gives me a great great service.

The code I use :

<asp:LinkButton ID="btn_fb" runat="server" data-provider="facebook" Text="Facebook connexion" OnClick="social_Click" EnableViewState="False"></asp:LinkButton>
 
        protected void social_Click(object sender, EventArgs e)
        {
            _log.InfoFormat("*** Session/Client ID : {0} / {1}", Session["session_id"], Session["client_id"]);

            //_registred = OAuthManager.RegisteredClients;
            //OAuthManager.RegisteredClients.Clear();

            string str_provider = ((LinkButton)sender).Attributes["data-provider"]
                , str_client_id = get_client_id(str_provider)
                , str_client_secret = get_client_secret(str_provider)
                , str_return_url = get_return_url();

            Dictionary<string, OAuthBase> _registred = new Dictionary<string, OAuthBase>();
            _registred = OAuthManager.RegisteredClients;

            if (!_registred.ContainsKey(str_provider))
            {
                switch (str_provider.ToLower())
                {
                    case "facebook":
                        FacebookClient _facebookcli = new FacebookClient(str_client_id, str_client_secret);
                        _facebookcli.Parameters.Add("display", "popup");                       
                        OAuthManager.RegisterClient(_facebookcli);
                        break;
                    /*
                    case "google":
                        GoogleClient _googlecli = new GoogleClient(str_client_id, str_client_secret);
                        ...
                        break;
                    default:
                        break;
                     */
                }
            }

            OAuthWeb.RedirectToAuthorization(str_provider, str_return_url);
        }

Many thank's Aleksey.

Nacer.
![copy1](https://cloud.githubusercontent.com/assets/11087251/6311201/2b01e4ac-b957-11e4-8256-bbe8d55d71cb.jpg)
![copy2](https://cloud.githubusercontent.com/assets/11087251/6311202/2b0a3e36-b957-11e4-86c6-60cddc955e9e.jpg)

**Comment by Nacer-** [comment]
code button
[<asp:LinkButton ID="btn_fb" runat="server" data-provider="facebook" Text="Connexion FaceBook" OnClick="social_Click" EnableViewState="False"></asp:LinkButton>]

**Comment by Nacer-** [comment]
\<asp:LinkButton ID="btn_fb" runat="server" data-provider="facebook" Text="Connexion FaceBook" OnClick="social_Click" EnableViewState="False"\>\</asp:LinkButton\>

**Comment by Nacer-** [comment]
code linkButton
\<asp:LinkButton ID="btn_fb" runat="server" data-provider="facebook" Text="Connexion FaceBook" OnClick="social_Click" EnableViewState="False"\>\</asp:LinkButton\>

**Comment by alekseynemiro** [comment]
> FacebookClient _facebookcli = new FacebookClient(str_client_id, str_client_secret);
> _facebookcli.Parameters.Add("display", "popup");                       
> OAuthManager.RegisterClient(_facebookcli);

Register **OAuth** clients better once when the application starts (**Application_Start** handler in the **Global.asax**).

```C#
public class Global : System.Web.HttpApplication
{

  protected void Application_Start(object sender, EventArgs e)
  {
    OAuthManager.RegisterClient
    (
      "facebook",
      "1435890426686808",
      "c6057dfae399beee9e8dc46a4182e8fd",
      parameters: new NameValueCollection { { "display", "popup" } }
    );

    OAuthManager.RegisterClient
    (
      "foursquare",
      "LHYZN1KUXN50L141QCQFNNVOYBGUE3G3FCWFZ3EEZTOZHY5Q",
      "HWXYFLLSS2IUQ0H4XNCDAZEFZKIU3MZRP5G55TNBDHRPNOQT",
      parameters: new NameValueCollection { { "display", "touch" } }
    );
  }

}
```
This is the best solution.

> we can not have a popup for Facebook authentication, there is a redirect to the site facebook and we remain necessarily on the same page

This can be done with **JavaScript**. The easiest way to use the **HyperLink**.

```HTML
<asp:HyperLink 
  NavigateUrl="~/RedirectToAuth.aspx?provider=facebook" 
  onclick="return Popup(this.href);" 
  ID="btnFacebook" 
  runat="server" 
  Text="[Connexion FaceBook]" 
  EnableViewState="False" 
/>

<script type="text/javascript">
	function Popup(url, width, height) {
		if(width == undefined || !width) { width = 550; }
		if(height == undefined || !height) { height = 450; }
		var x = (screen.width - width) / 2; 
		var y = (screen.height - height) / 2; 
		window.open
		(
			url, '_blank', 
			'toolbar=no,status=no,resizable=yes,' + 
			'scrollbars=yes,width=' + width + ',height=' + height + 
			',left=' + x + ',top=' + y
		);
		return false;
	}
</script>
```

On the page **RedirectToAuth.aspx** specify the code redirecting to provider.
```C#
protected void Page_Load(object sender, EventArgs e)
{
  if (String.IsNullOrEmpty(Request.QueryString["provider"]))
  {
    throw new ArgumentNullException("provider");
  }

  // build callback url
  string returnUrl = new Uri(Request.Url, "ExternalLoginResult.aspx").AbsoluteUri;
  // pop-up indicator for JavaScript code
  if (returnUrl.IndexOf("?") != -1)
  {
    returnUrl += "&";
  }
  else
  {
    returnUrl += "?";
  }
  returnUrl += "popup=true";

  // redirect to authorization page of the specified provider
  OAuthWeb.RedirectToAuthorization(Request.QueryString["provider"], returnUrl);
}
```
On the **ExternalLoginResult.aspx** you can check pop-up indicator and close pop-up window.
```HTML
<script type="text/javascript">
	if (window.location.search.indexOf('popup=true') != -1) {
		window.close();
	}
</script>
```
Or reaload in main window:
```HTML
<script type="text/javascript">
	if (window.location.search.indexOf('popup=true') != -1) {
		// reload main window
		window.opener.location = window.location;
		// close pop-up
		window.close();
	}
</script>
```
I [added](https://github.com/alekseynemiro/nemiro.oauth.dll/commit/d1ef817ffab77c1f3aa625f4e59d23e8cc9ffb99) a sample project: [AspWebFormsPopup](https://github.com/alekseynemiro/nemiro.oauth.dll/tree/master/src/AspWebFormsPopup).

**Comment by Nacer-** [comment]
Thank you Aleksey , it's more that I need :)

I have a question:

I have to make a single interface to manage different customers, each customer has a facebook account, a google account ... (each customer has a wifi zone in its local offering visitors a wifi access by hotspot captive portal, visitors must authenticate by facebook or google ... to access the Internet ...).

I'm in a situation where I need handle multiple facebook accounts, google accounts ... (multiple ApplicationId and ApplicationSecret).

if "Register OAuth clients better once when the application starts (Application_Start handler in the Global.asax)". is there a way to modify "ApplicationId" and  "ApplicationSecret" dynamically.

Is it okay to proceed as follow (in RedirectToAuth.aspx.cs)
		...
		string provider = Request.QueryString["provider"]
			, client_id = get_client_id(provider, Session["client_id"])
			, client_secret = get_client_secret(provider, Session["client_id"])
			, return_url = get_return_url(Session["client_id"]);
		
		OAuthManager.RegisteredClients.Clear();
		
		switch (provider)
                {
                       case "facebook":
				OAuthManager.RegisterClient
				(
				  "facebook",
				  client_id,
				  client_secret,
				  parameters: new NameValueCollection { { "display", "popup" } }
				);
			
			case "google":	
			...
		}

		OAuthWeb.RedirectToAuthorization(provider, return_url);

Many thank's Aleksey.
Nacer.

**Comment by alekseynemiro** [comment]
It's harder :-)


The **RegisterClient** does not allow to do it. You can register only one client with the same name.

You will have to make their own manager.

I made a sample project: [AspNetWebFormsMulticlients](https://github.com/alekseynemiro/nemiro.oauth.dll/tree/master/src/AspNetWebFormsMulticlients).

I added the ability to group clients.

Registration will still be carried out ONLY ONCE when the application starts (in **Global.asax**).
```C#
CustomOAuthManager.RegisterClient
(
  "default", // group name
  "facebook",
  "1435890426686808",
  "c6057dfae399beee9e8dc46a4182e8fd"
);

CustomOAuthManager.RegisterClient
(
  "popup", // other group name
  "facebook",
  "1435890426686808",
  "c6057dfae399beee9e8dc46a4182e8fd",
  parameters: new NameValueCollection { { "display", "popup" } }
);
```

You can specify a group in the link:
```HTML
<asp:HyperLink 
  NavigateUrl="~/RedirectToAuth.aspx?provider=facebook&group=default" 
  ID="btnFacebook" 
  runat="server" 
  Text="Default" 
  EnableViewState="False" 
/>

<asp:HyperLink 
  NavigateUrl="~/RedirectToAuth.aspx?provider=facebook&group=popup" 
  ID="btnFacebook2" 
  runat="server" 
  Text="Pop-up" 
  EnableViewState="False" 
/>
```
And redirect the user to an authentication page:
```C#
CustomOAuthWeb.RedirectToAuthorization
(
  Request.QueryString["group"], 
  Request.QueryString["provider"], 
  returnUrl
);
```
I hope it will help you.

I will try to implement the grouping in the next version of the library. I need more time to find the optimal solution.

Thank you for the idea!

**Comment by Nacer-** [comment]
Thank you Aleksey for your response.
That's great great great, CustomOAuthManager.RegisterClient is enough in my case and solve my situation,
I can identify the customer by id passed in the url of the hotspot.
eg  Customers connects to captive portal page template like:

	Customer_1	http://www.sitedemo.com/splash.html?id=Customer_1&....
	Customer_2 	http://www.sitedemo.com/splash.html?id=Customer_2&...
	...
	Customer_n	http://www.sitedemo.com/splash.html?id=Customer_n&...

Customer/Provider

	Customer		Provider	ApplicationID			ApplicationSecret
	*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
	Customer_1		facebook	Customer_1_fb_id		Customer_1_fb_secret
	Customer_2		facebook	Customer_2_fb_id		Customer_2_fb_secret
	...				...			...						...
	Customer_n		facebook	Customer_n_fb_id		Customer_n_fb_secret


	Customer_1		foursquare	Customer_1_frsq_id		Customer_1_frsq_secret
	Customer_2		foursquare	Customer_2_frsq_id		Customer_2_frsq_secret
	...				...			...						...
	Customer_n		foursquare	Customer_n_frsq_id		Customer_n_frsq_secret


And in Global.asax/Application_Start

	CustomOAuthManager.RegisterClient
	(
	  "Customer_1", 
	  "facebook",
	  "Customer_1_fb_id",
	  "Customer_1_fb_secret"
	  ...
	);

	CustomOAuthManager.RegisterClient
	(
	  "Customer_2", 
	  "facebook",
	  "Customer_2_fb_id",
	  "Customer_2_fb_secret"
	  ...
	);		

	...

	CustomOAuthManager.RegisterClient
	(
	  "Customer_n", 
	  "facebook",
	  "Customer_n_fb_id",
	  "Customer_n_fb_secret"
	  ...
	);



	CustomOAuthManager.RegisterClient
	(
	  "Customer_1", 
	  "foursquare",
	  "Customer_1_fb_id",
	  "Customer_1_fb_secret"
	);

	CustomOAuthManager.RegisterClient
	(
	  "Customer_2", 
	  "foursquare",
	  "Customer_2_fb_id",
	  "Customer_2_fb_secret"
	  ...
	);		

	...

	CustomOAuthManager.RegisterClient
	(
	  "Customer_n", 
	  "foursquare",
	  "Customer_n_fb_id",
	  "Customer_n_fb_secret"
	  ...
	);

In Global.asax/Session_Start, I identify may customer, and in template captive portal, I have only one facebook button, one foursquare button.

I think that for a better understanding, you can name "group name" by "client name" or "Relying Party (RP) name"; http://openid.net/specs/openid-connect-basic-1_0.html. We can have multiple "client" or "Relying Party (RP)" with the same "Open Provider OP".

I begin in the next two weeks the integration in a test environment, and will keep you informed.

It is I who thank you Aleksey.
Many thank's.

**Comment by alekseynemiro** [comment]
In the version **1.8** added the ability to specify the names of clients.
The release is made. You can [download](https://github.com/alekseynemiro/nemiro.oauth.dll/archive/v1.8.zip) the update.

```C#
// standard
OAuthManager.RegisterClient
(
  "facebook",
  "Customer_1_fb_id",
  "Customer_1_fb_secret"
);

// with client name
OAuthManager.RegisterClient
(
  "Customer_2",
  new FacebookClient
  (
    "Customer_2_fb_id", 
    "Customer_2_fb_secret"
  )
);

// or
var name = ClientName.Create("Customer_3", "Facebook");
OAuthManager.RegisterClient
(
  name,
  "Customer_3_fb_id", 
  "Customer_3_fb_secret"
);

// or
OAuthManager.RegisterClient
(
  ClientName.Create("Customer_4", "Facebook"),
  "Customer_4_fb_id", 
  "Customer_4_fb_secret"
);

// or a single line through the slash (I did not document this way)
OAuthManager.RegisterClient
(
  "Customer_5/facebook",
  "Customer_5_fb_id",
  "Customer_5_fb_secret"
);
```

For links, you can use **ClientName** as string:
```HTML
<asp:HyperLink 
  NavigateUrl="~/RedirectToAuth.aspx?provider=facebook" 
  ID="linkFacebook" 
  runat="server" 
  Text="Facebook 1" 
  EnableViewState="False" 
/>

<asp:HyperLink 
  NavigateUrl="~/RedirectToAuth.aspx?provider=Customer_2/facebook" 
  ID="linkFacebook2" 
  runat="server" 
  Text="Facebook 2" 
  EnableViewState="False" 
/>
```
or programmatically:

**ASPX**
```HTML
<asp:HyperLink 
  ID="linkFacebook3" 
  runat="server" 
  Text="Facebook 3" 
  EnableViewState="False" 
/>
```
**C#**
```C#
var name = ClientName.Create("Customer_3", "Facebook");
linkFacebook3.NavigateUrl = String.Format
(
  "~/RedirectToAuth.aspx?provider={0}", 
  name
);

// or hash
linkFacebook3.NavigateUrl = String.Format
(
  "~/RedirectToAuth.aspx?provider={0}", 
  name.Hash
);

// or split
linkFacebook3.NavigateUrl = String.Format
(
  "~/RedirectToAuth.aspx?provider={0}&clientName={1}", 
  name.ProviderName, 
  name.Key
);

// or split without ClientName class
linkFacebook3.NavigateUrl = String.Format
(
  "~/RedirectToAuth.aspx?provider={0}&clientName={1}", 
  "Facebook", 
  "Customer_3"
);

// etc.
```
Display a list of all clients (aspx):
```C#
<%foreach (var name in Nemiro.OAuth.OAuthManager.RegisteredClients.Keys) {%>
<a href="<%=ResolveUrl(String.Format("~/RedirectToAuth.aspx?provider={0}", name.Hash))%>">
<%=name.ProviderName%> (<%=name.Key%>)
<%}%>
