### ISSUE TITLE
Logout for Shared Computers (Revoke the Token)

### ISSUE THREAD

**Issue by sdbarron** [alekseynemiro/nemiro.oauth.dll#6]
I apologize because I'm not entirely sure if this is an issue with nemiro.oauth, oauth in general or if I'm just missing something important.

In addition to the existing table-based login for my site, I'm adding some social logins.  Thanks to nemiro.oauth, that's going pretty quickly and working just fine for me.

Unfortunately, many of my users are going to be using a shared computer.  I was planning to add some code to my existing Logout button to disconnect the user's social logins as well but I can't find a method to do that.  From what I've read elsewhere, I think I need to revoke the token for each.  But the token is abstracted away from me so I'm not sure how to do that.  Even if it is possible (and I suspect you will tell me it is :)), I wonder if you might consider making a method (in OAuthWeb?) for it to keep it simple, or at least add it to Problems and Solutions.

Keep up the good work!

**Comment by alekseynemiro** [comment]
Unfortunately, not all providers support this feature. So I did not become do it.

But in the future I am planning to return to this issue and make updating and deactivation of the access token.

Thank you for your message! 
This will speed up the process and maybe I will find a solution in version **1.9**.

**Comment by sdbarron** [comment]
Thanks!

I really appreciate your efforts so far - and today's new release!

**Comment by sdbarron** [comment]
Were you thinking of adding a method to the client base class or just implementing in each provider client?  You mentioned that not all providers support this feature so, while I I'm experimenting, I'm adding this to just the provider client(s) for now.  Given the unlikelihood of getting a defined response, I wasn't sure how to implement a base method that would be distinguishable from an implemented override.  But, if you decide to add something to the base, it's no big deal - this can just be the override (for Google at least).  :)

```c#
/// <summary>
/// Revoke the token (a.k.a. log off)
/// </summary>
/// <returns>
/// <para>Nothing</para>
/// </returns>
public void RevokeToken()
    {
        // execute the request
        var result = OAuthUtility.Get("https://accounts.google.com/o/oauth2/revoke?token=" +         
                              this.AccessToken["access_token"].ToString());
    }
```

I'd be happy to help add these to as many provider client implementations as we can (once you approve a template of how it should work). 

...or would it be cleaner/better for me to just go get XxxxxxClient.AccessToken and do this in my code independently?

**Comment by alekseynemiro** [comment]
I have already started work in this direction. At the moment, there is only an outline.

**OAuthBase**
```C#
public virtual bool SupportRevokeToken
{
  get
  {
    return false;
  }
}

public virtual bool SupportRefreshToken
{
  get
  {
    return false;
  }
}

public virtual RequetResult RevokeToken(string accessToken = null) 
{
  throw new NotSupportedException();
}

public virtual AccessToken RefreshToken(string accessToken = null)
{
  throw new NotSupportedException();
}
```

For each provider will have to write the code for refreshing and/or revoking an access token.

I have not yet fully decided on types and method names :-)

A little later, I will update the code in **GitHub**.

**Comment by sdbarron** [comment]
Awesome, thanks!

**Comment by sdbarron** [comment]
I think I've come to the realization that it's not (just) revoking the token that I need in order to log users out.

When I click on the button to login, the provider remembers who I am and helpfully logs me in again.  If one of my users saves their login on the shared computer, the next person won't be able to login.  

Google has an authorization parameter of approval_prompt=force - and that seems to take care of it.  Are you aware of any other providers which support something like that?  Without it, I'm somewhat sunk (at least for people using the shared computer).

**Comment by alekseynemiro** [comment]
**approval_prompt=force** - is to re-request permissions.

You can specify any parameters when registering the client:
```C#
OAuthManager.RegisterClient
(
  new GoogleClient
  (
    "1058655871432-83b9micke7cll89jfmcno5nftha3e95o.apps.googleusercontent.com",
    "AeEbEGQqoKgOZb41JUVLvEJL"
  )
  {
    Parameters = new NameValueCollection { { "approval_prompt", "force" } }
  }
);
```

But if your browser cookies remain, it will not help. For safety, the user must have an account on a shared computer and/or should not save cookies.

**Comment by alekseynemiro** [comment]
I checked, revoke access token programmatically is available only for: **Facebook**, **Dropbox** and **Google**.

**Comment by sdbarron** [comment]
Thanks!  I think that's going to be another nail in the coffin for me.

**Comment by alekseynemiro** [comment]
Just do not save the access token in the application settings. Use memory. And clearing cookies.
