### ISSUE TITLE
Help with Yandex authorization

### ISSUE THREAD

**Issue by Jericho-kd** [alekseynemiro/nemiro.oauth.dll#8]
Добрый вечер, Алексей.
Пытаюсь разобраться с авторизацией на Yandex. 
Опыта работы с OAuth, HTTP-запросами(POST, GET) нет. Отсюда и возникают следующие вопросы:
1) После выполнения запроса System.Diagnostics.Process.Start(yandex.AuthorizationUrl) на странице в браузере отображается "Код подтверждения". Я так понимаю, что после получения кода подтверждения мы автоматически получаем и "токен доступа", с которым в дальнейшем и работаем? Или же нам надо посылать POST-запрос с кодом подтверждения для получения этого токена?
2) Допустим, мы получили "токен доступа". Теперь мне надо, к примеру, послать запрос на получение информации о моем Yandex.Disk. Этот "токен доступа" я должен передавать в GET-запросе как один из параметров или механизм запросов реализован как-то по-другому?
Прошу Вас ответить на эти вопросы по мере возможности.
P.S. Прошу прощения за то, что пишу на русском. Если это критично, то могу попробовать пересоздать issue на английском языке.

**Comment by alekseynemiro** [comment]
Код нужно извлечь и преобразовать в маркер доступа (**access token**).

Маркер доступа (**access token**) нужно использовать для всех запросов к **API**. Для Яндекс, маркер следует передавать в **HTTP**-заголовке **Authorization**. 
Например: `Authorization: OAuth маркерДоступа`. 

Если для работы с **API** Яндекс использовать библиотеку **Nemiro.OAuth**, то пример можно найти по следующей ссылке:
https://github.com/alekseynemiro/nemiro.oauth.dll/blob/master/src/Test.OAuthWeb/Controllers/Yandex.cs

Для **Windows Forms** есть готовые формы:
https://github.com/alekseynemiro/Nemiro.OAuth.LoginForms

Пример для Яндекс:
```C#
// создаем форму
var login = new YandexLogin("appid", "appsecret") { Owner = this }; // Owner  - текущая форма, чтобы форма авторизации была сверху
// показываем окно авторизации
login.ShowDialog();
// если все прошло успешно, получаем маркер доступа (access token)
if (login.IsSuccessfully)
{
  string accessToken = login.AccessToken.Value;
  MessageBox.Show("Получен маркер доступа: " + accessToken);
  // маркер можно сохранить в настройки приложения
  // http://www.youtube.com/watch?v=_s_XSiRTL90
  // Properties.Settings.Default.AccessToken = accessToken;
  // Properties.Settings.Default.Save();
  // и использовать при работе с Яндекс.Диск
  var result = OAuthUtility.Get
  (
    "https://cloud-api.yandex.net/v1/disk/resources",
    new HttpParameterCollection
    {
      { "path", "/" } // путь
    },
    authorization: String.Format("OAuth {0}", accessToken) // или брать из настроек Properties.Settings.Default.AccessToken, если использовать сохранение в настройки
  );
  if (result.StatusCode == 200)
  {
    MessageBox.Show(result.ToString());
  }
  else
  {
    MessageBox.Show(result["message"].ToString(), "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
  }
}
```
Вот еще один пример работы с Яндекс.Диск:
https://github.com/alekseynemiro/Nemiro.OAuth.LoginForms/tree/master/src/TestNet45
(используются асинхронные методы отправки веб-запросов)

**Comment by Jericho-kd** [comment]
Здравствуйте, Алексей.
Стоит задача при каждом запуске программы запрашивать форму авторизации( ввод логина/пароля). Я так понимаю,что для этого нам надо отзывать старый "маркер доступа", а затем получать новый.
Подскажите, как реализовать отзыв старого "маркера"(просто его удалять или как-то обновлять).

P.S. Повторно запрашивать форму авторизации у меня получается только когда, к примеру, в Яндекс.Паспорте я выбираю пункт "Выйти на всех компьютерах", потом при запуске программы обнуляю строку с "маркером доступа". И в итоге получаю окно авторизации, в котором просят заново ввести логин/пароль.

**Comment by alekseynemiro** [comment]
К сожалению, Яндекс не поддерживает программный отзыв маркера доступа (**access token**).
В **WebBrowser** нужно отдельно **Cookies** удалять, чтобы можно было пройти авторизацию повторно. Это было запланировано на реализацию, но пока нормальный/оптимальный способ не найден.

По следующим ссылкам можно найти варианты удаления **Cookies** из **WebBrowser**:
http://stackoverflow.com/questions/912741/how-to-delete-cookies-from-windows-form
http://stackoverflow.com/questions/21265674/delete-cookies-in-webbrowser-without-restart
http://mdb-blog.blogspot.ru/2013/02/c-winforms-webbrowser-clear-all-cookies.html

**Comment by Jericho-kd** [comment]
Алексей, я собираюсь создать библиотеку и включить в нее методы, отвечающие за авторизацию и обращение к Yandex.Disk (в будущем, библиотеку можно будет подключать к различным типам приложений, в том числе и к консольным) и отсюда у меня возникают следующие вопросы:
1) Маркер доступа. Если мне не нужно программно хранить "маркер доступа", то, я так понимаю, можно напрямую обращаться к маркеру, предварительно объявив объект класса YandexLogin?(и места в коде, где мы используем маркер просто изменить на login.AccessToken.Value);
2) Авторизация. В своей библиотеке я создаю метод GetAccessToken(в котором я вызываю форму авторизации). При подключении библиотеки к проекту и последующем вызове GetAccessToken я получаю Exception со следующим текстом("Необработанное исключение типа "System.InvalidOperationException" в System.Windows.Forms.dll
Дополнительные сведения: Недопустимая операция в нескольких потоках: попытка доступа к элементу управления "webBrowser1" не из того потока, в котором он был создан."). Я так понимаю, что какая-то проблема с потоками. Не подскажете, как можно этого избежать?  
3) Можно ли обойтись без ввода информации в форме авторизации? Например, создать переменные, в которых будут храниться логин и пароль к нужному аккаунту. И при вызове формы авторизации автоматически заполнять поля логин/пароль значениями из переменных.
Спасибо за внимание.

**Comment by alekseynemiro** [comment]
1. Лучше передать маркер в отдельную переменную. На случай ликвидации формы.

2. Нужно вернуться в свой поток. Без кода ничего конкретного не скажу. 

Примерно так:
```C#
private void GetAccessToken()
{
      if (this.InvokeRequired)
      {
        this.Invoke(new Action(this.GetAccessToken));
        return;
      }

      // тут можно безопасно работать с элементами формы
}
```

3\. Можно. Но это не всегда является законным :-) В соглашении Яндекс для разработчиков может быть правило на этот счет.

Нужно загрузить форму авторизации в **WebBrowser**, найти поля для ввода имени и пароля, найти кнопку авторизации и вызвать **click**. Но следует учитывать, что Яндекс может захотеть проверить пользователя на человечность и заставить вводить капчу. 

Пример поиска элементов можно посмотреть в обработчике загрузки страницы в **WebBrowser**.

**Comment by alekseynemiro** [comment]
Посмотрел на форму Яндекс. Примерно такой код будет (без учета ошибок и появления капчи):
```C#
private void webBrowser1_DocumentCompleted(object sender, WebBrowserDocumentCompletedEventArgs e)
{
  // автоматический вход, с программным указанием логина и пароля
  if (e.Url.ToString().Contains("https://passport.yandex.ru/auth"))
  {
    // находим поля для логина и пароля и указываем нужные данные
    webBrowser1.Document.GetElementById("login").SetAttribute("value", "логин");
    webBrowser1.Document.GetElementById("passwd").SetAttribute("value", "пароль");
    // отправляем форму (подразумевается наличие всего одной формы на странице)
    webBrowser1.Document.Forms[0].InvokeMember("submit");
    return;
  }

  // стандартный код поиска кода и получения маркера доступа

  // waiting for results
  if (e.Url.Query.IndexOf("code=") != -1 || e.Url.Query.IndexOf("oauth_verifier=") != -1)
  {
    // is result
    var v = UniValue.ParseParameters(e.Url.Query.Substring(1));
    if (v.ContainsKey("code"))
    {
      this.GetAccessToken(v["code"].ToString());
    }
    else
    {
      this.GetAccessToken(v["oauth_verifier"].ToString());
    }
    return;
  }
  // access denied
  if (!String.IsNullOrEmpty(e.Url.Query) && e.Url.Query.IndexOf("error=access_denied") != -1)
  {
    this.Close();
  }
  // custom handler
  if (typeof(ILoginForm).IsAssignableFrom(this.GetType()))
  {
    ((ILoginForm)this).WebDocumentLoaded(this.webBrowser1, e.Url);
  }
}
```

**Comment by Jericho-kd** [comment]
Спасибо, Алексей. Проверю сразу как будет возможность.

**Comment by Jericho-kd** [comment]
Алексей, возвращаясь к вопросу о возникновении исключения при вызове формы авторизации, хотел бы привести пример кода:
Это 2 метода в моей библиотеке:

        public void Connect()
        {
            if (String.IsNullOrEmpty(Properties.Settings.Default.AccessToken))
            {
                GetAccessToken();
            }
            else
            {
                Authorization = new HttpAuthorization(AuthorizationType.OAuth,                      Properties.Settings.Default.AccessToken);//Properties.Settings.Default.AccessToken);
            }
        }

        public void GetAccessToken()
        {
            login.ShowDialog();

            if (login.IsSuccessfully)
            {
                this.Authorization = new HttpAuthorization(AuthorizationType.OAuth,                                           Properties.Settings.Default.AccessToken);//Properties.Settings.Default.AccessToken);
            }
            else
            {
                Console.WriteLine("Error");
            }
        }

При последующем вызове метода Connect() из моего приложения(приложение консольное) 
 YandexAuth ya = new YandexAuth();
 ya.Connect();
при переходе в GetAccessToken() и вызове login.ShowDialog() я и получаю вышеописанное исключение. Я не работал с потоками, поиск информации в интернете не дает положительных результатов.
Или может просто постараться авторизоваться без этой формы, а, к примеру, выполнить соответствующий запрос к серверу(если возможно, то прошу вас подсказать)

**Comment by alekseynemiro** [comment]
А где создается форма? (переменная **login**)

По идее, в консольных приложениях подобных проблем быть не должно, если только форма не была создана в другом потоке.

**Comment by Jericho-kd** [comment]
Переменная login создается как private-член в моей библиотеке.

**Comment by alekseynemiro** [comment]
Да, **WebBrowser** особый компонент и с ним нельзя так просто работать в консольных приложениях.

```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Nemiro.OAuth.LoginForms;
using Nemiro.OAuth;
using System.Threading;
using System.Windows.Forms;
using System.Diagnostics;

namespace OAuthIssueComment154291399
{

  class Program
  {

    static void Main(string[] args)
    {
      // убиваем всю куку
      var p = Process.Start("cmd.exe", "/C RunDll32.exe InetCpl.cpl,ClearMyTracksByProcess 255");
      p.WaitForExit();
      // --

      var ya = new Program();
      ya.Connect();

      Console.ReadKey();
    }

    private HttpAuthorization Authorization;

    public Program()
    {
    }

    public void Connect()
    {
      if (String.IsNullOrEmpty(Properties.Settings.Default.AccessToken))
      {
        this.GetAccessToken();
      }
      else
      {
        this.Authorization = new HttpAuthorization(AuthorizationType.OAuth, Properties.Settings.Default.AccessToken);
      }
    }

    public void GetAccessToken()
    {
      Console.WriteLine("Getting access token.");

      // создаем поток
      var t = new Thread(() =>
      {
        // создаем форму
        var login = new YandexLogin("0ee5f0bf2cd141a1b194a2b71b0332ce", "59d76f7c09b54ad38e6b15f792da7a9a");

        // показываем форму
        login.ShowDialog();

        // обрабатываем результат
        if (login.IsSuccessfully)
        {
          Properties.Settings.Default.AccessToken = login.AccessTokenValue;
          Properties.Settings.Default.Save();
          Console.WriteLine("Access token: {0}", login.AccessTokenValue);
        }
        else
        {
          Console.WriteLine("Error");
        }
      });
      // задаем однопоточный апартамент
      // https://msdn.microsoft.com/ru-ru/library/system.threading.apartmentstate%28v=vs.110%29.aspx
      t.SetApartmentState(ApartmentState.STA);
      // запускаем поток
      t.Start();
    }

  }

}
```

**Comment by alekseynemiro** [comment]
В новой версии библиотеки реализован выход.

Чтобы использовать функцию выхода, достаточно при создании экземпляра формы указать в последнем параметре значение **true**:
```C#
var login = new YandexLogin
(
  "0ee5f0bf2cd141a1b194a2b71b0332ce", 
  "59d76f7c09b54ad38e6b15f792da7a9a", 
  true
);
```

Перед загрузкой формы авторизации и после успешного прохождения авторизации будет выполняться выход. При следующем заходе пользователю придется вводить имя и пароль снова.
