### ISSUE TITLE
System.NullReferenceException' occurred in Nemiro.OAuth.LoginForms.dll

### ISSUE THREAD

**Issue by nishantpatel2607** [alekseynemiro/nemiro.oauth.dll#9]
Getting error in c# winforms app when trying to get access token from dropbox.

System.NullReferenceException was unhandled
Message: An unhandled exception of type 'System.NullReferenceException' occurred in Nemiro.OAuth.LoginForms.dll
Additional information: Object reference not set to an instance of an object.

**Comment by alekseynemiro** [comment]
DropBox have changed HTML.
Fixed. Without release.

Thank you for message!

https://github.com/alekseynemiro/Nemiro.OAuth.LoginForms/commit/fb572584942516c05ba1ae7ff39ca8db1e8e6dbf

https://github.com/alekseynemiro/Nemiro.OAuth.LoginForms/blob/master/src/Nemiro.OAuth.LoginForms/LoginForms/DropboxLogin.cs

**Comment by alekseynemiro** [comment]
Relesed v.1.4
